language: go

os:
  - linux

go:
  - 1.11.5

services:
  - docker


before_script: cd build
jobs:
  include:
    - stage: Build Citrix Node Controller
      script:
        - make build
    - stage: Unit Testing Citrix Node Controller
      script:
        - make test
    - stage: Publish Citrix Node Controller 
      script:
        - make publish
