language: go

os:
  - linux

services:
  - docker

before_script: cd build
jobs:
  include:
    - stage: Build Citrix Node Controller
      script:
        - make build
    - stage: Unit Test Citrix Node COntroller
      script:
        - make test
