dist: xenial

language: go

go:
  - 1.11.5

services:
  - docker

sudo: required

env:
  global:
     - CHANGE_MINIKUBE_NONE_USER=true
     - MINIKUBE_WANTREPORTERRORPROMPT=false
     - MINIKUBE_WANTUPDATENOTIFICATION=false
     - KUBECONFIG=/home/travis/.kube/config

before_script: cd build

jobs:
  include:
    - stage: Unit Testing Citrix Node Controller
       - stage: Integration Tests
         before_script:
             - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        
             - go get sigs.k8s.io/kind
        
             - kind create cluster

             - export KUBECONFIG="$(kind get kubeconfig-path)"
        
         script: make test
    - stage: Build Citrix Node Controller
      script:
        - make build

    - stage: Publish Citrix Node Controller 
      script:
        - make publish
