dist: xenial

language: go

go:
  - 1.11.5

services:
  - docker

sudo: required

env:
  global:
     - CHANGE_MINIKUBE_NONE_USER=true
     - MINIKUBE_WANTREPORTERRORPROMPT=false
     - MINIKUBE_WANTUPDATENOTIFICATION=false
     - KUBECONFIG=/home/travis/.kube/config

before_script: cd build

jobs:
  include:
    - stage: Unit Testing Citrix Node Controller
      script: 
        - make test

    - stage: Code Coverage of Citrix Node Controller
      script: 
        - make coverage
        - bash <(curl -s https://codecov.io/bash)

    - stage: Build Citrix Node Controller
      script:
        - make build

    - stage: Publish Citrix Node Controller 
      script:
        - make publish

