dist: xenial

language: go

go:
  - 1.11.5

services:
  - docker

sudo: required

env:
  global:
     - CHANGE_MINIKUBE_NONE_USER=true
     - MINIKUBE_WANTREPORTERRORPROMPT=false
     - MINIKUBE_WANTUPDATENOTIFICATION=false
     - KUBECONFIG=/home/travis/.kube/config

before_script: cd build

jobs:
  include:
    - stage: Create kubernetes cluster 
      script:
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube
        - kubectl cluster-info
        - echo $HOME
        - export KUBECONFIG=$HOME/.kube/config
    
    - stage: Build Citrix Node Controller
      script:
        - make build

    - stage: Unit Testing Citrix Node Controller
      script:
        - make test

    - stage: Publish Citrix Node Controller 
      script:
        - make publish
