language: go

os:
  - linux

go:
  - 1.11.5

services:
  - docker

env:
  global:
    - NS_IP=citrix.node.controller.com
    - NS_VTEP_MAC=aa:aa:aa:aa:aa
    - NS_LOGIN=admin
    - NS_PASSWORD=test
      

before_script: cd build
jobs:
  include:
    - stage: Build Citrix Node Controller
      script:
        - make build
    - stage: Unit Test Citrix Node COntroller
      script:
        - make test
