language: go

os:
  - linux

go:
  - 1.11.5

services:
  - docker

sudo: required

go_import_path: k8s.io/minikube

before_script:
- sudo minikube start 
- cd build

jobs:
  include:
    - stage: Create kubernetes cluster 
        - kubectl cluster-info
    
    - stage: Build Citrix Node Controller
      script:
        - make build

    - stage: Unit Testing Citrix Node Controller
      script:
        - make test

    - stage: Publish Citrix Node Controller 
      script:
        - make publish
