dist: xenial

language: go

go:
  - 1.11.5

services:
  - docker

sudo: required


before_script:
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube
- sudo cp minikube /usr/local/bin && rm minikube
- sudo minikube start --vm-driver=none 
- cd build

jobs:
  include:
    - stage: Create kubernetes cluster 
        - kubectl cluster-info
    
    - stage: Build Citrix Node Controller
      script:
        - make build

    - stage: Unit Testing Citrix Node Controller
      script:
        - make test

    - stage: Publish Citrix Node Controller 
      script:
        - make publish
