apiVersion: v1
kind: Namespace
metadata:
  name: citrix
  labels:
    name: citrix
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: citrix-node-controller
  namespace: citrix
data:
  operation: "ADD"
